/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System */
        get: operations["system_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step Session */
        post: operations["step_session_sessions__session_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/run-until-idle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Until Idle */
        post: operations["run_until_idle_sessions__session_id__run_until_idle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/case-notebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Notebook */
        get: operations["get_case_notebook_sessions__session_id__case_notebook_get"];
        put?: never;
        /** Case Notebook */
        post: operations["case_notebook_sessions__session_id__case_notebook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_sessions__session_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Component */
        get: operations["component_sessions__session_id__components__component_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe */
        post: operations["probe_sessions__session_id__probes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/components/{component_id}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Component Interaction */
        post: operations["component_interaction_sessions__session_id__components__component_id__interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttackerProfile
         * @description Demo principal profile used to build a probe.
         * @enum {string}
         */
        AttackerProfile: "unknown" | "wrong_role" | "valid_but_malicious";
        /**
         * AuditChainSnapshot
         * @description Audit-chain state exposed to the UI.
         */
        AuditChainSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Event Count */
            event_count: number;
            /** Latest Event Hash */
            latest_event_hash?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * BankId
         * @description Known bank identifiers plus the federation runtime.
         * @enum {string}
         */
        BankId: "bank_alpha" | "bank_beta" | "bank_gamma" | "federation";
        /**
         * CaseNotebookReportSnapshot
         * @description Generated case notebook plus static HTML report views.
         */
        CaseNotebookReportSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Scenario Id */
            scenario_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Terminal Code */
            terminal_code?: string | null;
            /** Terminal Reason */
            terminal_reason?: string | null;
            /** Notebook Path */
            notebook_path: string;
            /** Artifact Path */
            artifact_path: string;
            /** Notebook Html Path */
            notebook_html_path: string;
            /** Artifact Html Path */
            artifact_html_path: string;
            /** Notebook Html */
            notebook_html: string;
            /** Artifact Html */
            artifact_html: string;
            /** Cell Count */
            cell_count: number;
            /** Detail */
            detail: string;
        };
        /**
         * ComponentId
         * @description Inspectable node or mechanism ids shown in the judge console.
         * @enum {string}
         */
        ComponentId: "A1" | "A2" | "F1" | "bank_alpha.A3" | "bank_beta.A3" | "bank_gamma.A3" | "P7" | "F2" | "F3" | "F4" | "F5" | "lobster_trap" | "litellm" | "signing" | "envelope" | "replay" | "route_approval" | "dp_ledger" | "audit_chain";
        /**
         * ComponentInteractionKind
         * @description Safe component-directed actions from the judge console.
         * @enum {string}
         */
        ComponentInteractionKind: "prompt" | "inspect" | "explain_state" | "safe_input";
        /**
         * ComponentInteractionRequest
         * @description Safe component interaction request for the judge console.
         */
        ComponentInteractionRequest: {
            interaction_kind: components["schemas"]["ComponentInteractionKind"];
            /** Payload Text */
            payload_text?: string | null;
            /** @default valid_but_malicious */
            attacker_profile: components["schemas"]["AttackerProfile"];
            target_instance_id?: components["schemas"]["TrustDomainId"] | null;
            /**
             * Route Through Lobster Trap
             * @default true
             */
            route_through_lobster_trap: boolean;
            /** Model Route */
            model_route?: string | null;
        };
        /**
         * ComponentInteractionResult
         * @description Outcome of one safe component-directed interaction.
         *
         *     Two boolean fields disambiguate "we got it" from "we ran it":
         *
         *     * ``accepted`` -- the request passed validation and was recorded.
         *       False only when the component is not built yet (and therefore
         *       cannot be interacted with at all).
         *     * ``executed`` -- a live handler actually ran and produced
         *       meaningful output. PROMPT / SAFE_INPUT either call a live
         *       model-route harness or execute the target component's typed
         *       boundary check.
         *
         *     The UI uses both to distinguish "successfully inspected" from
         *     "queued for a future handler" from "refused / not built".
         */
        ComponentInteractionResult: {
            /**
             * Interaction Id
             * Format: uuid
             */
            interaction_id?: string;
            interaction_kind: components["schemas"]["ComponentInteractionKind"];
            target_component: components["schemas"]["ComponentId"];
            target_instance_id?: components["schemas"]["TrustDomainId"] | null;
            attacker_profile: components["schemas"]["AttackerProfile"];
            /** Accepted */
            accepted: boolean;
            /** Executed */
            executed: boolean;
            status: components["schemas"]["SnapshotStatus"];
            blocked_by?: components["schemas"]["SecurityLayer"] | null;
            /** Reason */
            reason: string;
            timeline_event: components["schemas"]["TimelineEventSnapshot"];
            component_snapshot?: components["schemas"]["ComponentSnapshot"] | null;
            /** Available After */
            available_after?: string | null;
        };
        /**
         * ComponentReadinessSnapshot
         * @description Readiness for one component in the demo stack.
         */
        ComponentReadinessSnapshot: {
            component_id: components["schemas"]["ComponentId"];
            /** Label */
            label: string;
            status: components["schemas"]["SnapshotStatus"];
            /** Available After */
            available_after?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * ComponentSnapshot
         * @description Generic component inspector payload.
         */
        ComponentSnapshot: {
            component_id: components["schemas"]["ComponentId"];
            status: components["schemas"]["SnapshotStatus"];
            /** Title */
            title: string;
            /** Fields */
            fields?: components["schemas"]["SnapshotField"][];
            signing?: components["schemas"]["SigningStateSnapshot"] | null;
            envelope?: components["schemas"]["EnvelopeVerificationSnapshot"] | null;
            replay?: components["schemas"]["ReplayCacheSnapshot"] | null;
            route_approval?: components["schemas"]["RouteApprovalSnapshot"] | null;
            dp_ledger?: components["schemas"]["DpLedgerSnapshot"] | null;
            provider_health?: components["schemas"]["ProviderHealthSnapshot"] | null;
            audit_chain?: components["schemas"]["AuditChainSnapshot"] | null;
        };
        /**
         * DpLedgerEntrySnapshot
         * @description One requester/bank rho budget row.
         */
        DpLedgerEntrySnapshot: {
            /** Requester Key */
            requester_key: string;
            responding_bank_id: components["schemas"]["BankId"];
            /** Rho Spent */
            rho_spent: number;
            /** Rho Remaining */
            rho_remaining: number;
            /** Rho Max */
            rho_max: number;
        };
        /**
         * DpLedgerSnapshot
         * @description UI-facing DP ledger state.
         */
        DpLedgerSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Entries */
            entries?: components["schemas"]["DpLedgerEntrySnapshot"][];
            /** Detail */
            detail: string;
        };
        /**
         * EnvelopeVerificationSnapshot
         * @description Last signed-envelope verification result visible to the UI.
         */
        EnvelopeVerificationSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Message Type */
            message_type?: string | null;
            /** Sender Agent Id */
            sender_agent_id?: string | null;
            /** Recipient Agent Id */
            recipient_agent_id?: string | null;
            /** Body Hash */
            body_hash?: string | null;
            /**
             * Signature Status
             * @default not_checked
             * @enum {string}
             */
            signature_status: "valid" | "invalid" | "missing" | "not_checked";
            /**
             * Freshness Status
             * @default not_checked
             * @enum {string}
             */
            freshness_status: "fresh" | "expired" | "not_checked";
            blocked_by?: components["schemas"]["SecurityLayer"] | null;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthSnapshot
         * @description Minimal readiness response for process health probes.
         */
        HealthSnapshot: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * ProbeKind
         * @description Controlled adversarial inputs available through the demo API.
         * @enum {string}
         */
        ProbeKind: "prompt_injection" | "unsigned_message" | "body_tamper" | "wrong_role" | "replay_nonce" | "route_mismatch" | "unsupported_query_shape" | "budget_exhaustion";
        /**
         * ProbeRequest
         * @description Controlled attack request sent through a real security boundary.
         */
        ProbeRequest: {
            probe_kind: components["schemas"]["ProbeKind"];
            target_component: components["schemas"]["ComponentId"];
            /** @default valid_but_malicious */
            attacker_profile: components["schemas"]["AttackerProfile"];
            /** Payload Text */
            payload_text?: string | null;
            target_instance_id?: components["schemas"]["TrustDomainId"] | null;
            /**
             * Route Through Lobster Trap
             * @default true
             */
            route_through_lobster_trap: boolean;
        };
        /**
         * ProbeResult
         * @description Outcome of one adversarial probe.
         *
         *     Carries the full state bundle that ``DemoControlService.run_probe``
         *     commits to the session under one short critical section. Handlers
         *     set the relevant ``envelope`` / ``route_approval`` / ``dp_ledger``
         *     fields here instead of mutating session state directly, so probe
         *     execution can run outside the session lock.
         */
        ProbeResult: {
            /**
             * Probe Id
             * Format: uuid
             */
            probe_id?: string;
            probe_kind: components["schemas"]["ProbeKind"];
            target_component: components["schemas"]["ComponentId"];
            attacker_profile: components["schemas"]["AttackerProfile"];
            /** Accepted */
            accepted: boolean;
            blocked_by: components["schemas"]["SecurityLayer"];
            /** Reason */
            reason: string;
            envelope?: components["schemas"]["EnvelopeVerificationSnapshot"] | null;
            replay?: components["schemas"]["ReplayCacheSnapshot"] | null;
            route_approval?: components["schemas"]["RouteApprovalSnapshot"] | null;
            dp_ledger?: components["schemas"]["DpLedgerSnapshot"] | null;
            timeline_event: components["schemas"]["TimelineEventSnapshot"];
        };
        /**
         * ProviderHealthSnapshot
         * @description Provider and proxy health with secrets redacted.
         */
        ProviderHealthSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Lobster Trap Configured */
            lobster_trap_configured: boolean;
            /** Litellm Configured */
            litellm_configured: boolean;
            /** Gemini Api Key Present */
            gemini_api_key_present: boolean;
            /** Openrouter Api Key Present */
            openrouter_api_key_present: boolean;
            /**
             * Secret Values
             * @default redacted
             * @constant
             */
            secret_values: "redacted";
            /** Detail */
            detail: string;
        };
        /**
         * ReplayCacheEntrySnapshot
         * @description Redacted replay-cache entry for UI inspection.
         */
        ReplayCacheEntrySnapshot: {
            /** Principal Id */
            principal_id: string;
            /** Nonce Hash */
            nonce_hash: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * ReplayCacheSnapshot
         * @description Redacted replay-cache state for UI inspection.
         */
        ReplayCacheSnapshot: {
            /** Entries */
            entries?: components["schemas"]["ReplayCacheEntrySnapshot"][];
        };
        /**
         * RouteApprovalSnapshot
         * @description Route-approval binding state for UI inspection.
         */
        RouteApprovalSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Query Id */
            query_id?: string | null;
            route_kind?: components["schemas"]["RouteKind"] | null;
            /** Approved Query Body Hash */
            approved_query_body_hash?: string | null;
            /** Computed Query Body Hash */
            computed_query_body_hash?: string | null;
            requester_bank_id?: components["schemas"]["BankId"] | null;
            responder_bank_id?: components["schemas"]["BankId"] | null;
            /**
             * Binding Status
             * @default not_checked
             * @enum {string}
             */
            binding_status: "matched" | "mismatched" | "not_checked";
            /** Detail */
            detail: string;
        };
        /**
         * RouteKind
         * @description F1-to-A3 route kinds with different disclosure semantics.
         * @enum {string}
         */
        RouteKind: "peer_314b" | "local_contribution";
        /**
         * SecurityLayer
         * @description Layer that accepted, blocked, or will later handle a probe.
         * @enum {string}
         */
        SecurityLayer: "schema" | "signature" | "allowlist" | "freshness" | "replay" | "route_approval" | "lobster_trap" | "a3_policy" | "p7_budget" | "not_built" | "accepted" | "internal_error";
        /**
         * SessionCreateRequest
         * @description Create or reset one demo session.
         */
        SessionCreateRequest: {
            /**
             * Scenario Id
             * @default s1_structuring_ring
             */
            scenario_id: string;
            /** @default stub */
            mode: components["schemas"]["SessionMode"];
        };
        /**
         * SessionMode
         * @description Execution mode selected for a demo session.
         * @enum {string}
         */
        SessionMode: "stub" | "live" | "live_with_stub_fallback";
        /**
         * SessionSnapshot
         * @description Summary of one demo session.
         */
        SessionSnapshot: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Scenario Id */
            scenario_id: string;
            mode: components["schemas"]["SessionMode"];
            /** Phase */
            phase: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Components */
            components: components["schemas"]["ComponentReadinessSnapshot"][];
            /** Latest Events */
            latest_events?: components["schemas"]["TimelineEventSnapshot"][];
        };
        /**
         * SigningStateSnapshot
         * @description Public signing state. Private keys are never exposed.
         */
        SigningStateSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Known Signing Key Ids */
            known_signing_key_ids: string[];
            /**
             * Private Key Material Exposed
             * @default false
             * @constant
             */
            private_key_material_exposed: false;
            /** Last Verified Key Id */
            last_verified_key_id?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * SnapshotField
         * @description One redacted key/value field for generic UI cards.
         */
        SnapshotField: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
        };
        /**
         * SnapshotStatus
         * @description Readiness state for one inspectable subsystem.
         * @enum {string}
         */
        SnapshotStatus: "live" | "blocked" | "not_built" | "pending" | "simulated" | "error";
        /**
         * SystemSnapshot
         * @description Global API/system readiness.
         */
        SystemSnapshot: {
            status: components["schemas"]["SnapshotStatus"];
            /** Components */
            components: components["schemas"]["ComponentReadinessSnapshot"][];
            provider_health: components["schemas"]["ProviderHealthSnapshot"];
            /** Detail */
            detail: string;
        };
        /**
         * TimelineEventSnapshot
         * @description One event in the demo timeline.
         */
        TimelineEventSnapshot: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id?: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            component_id: components["schemas"]["ComponentId"];
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            status: components["schemas"]["SnapshotStatus"];
            blocked_by?: components["schemas"]["SecurityLayer"] | null;
        };
        /**
         * TrustDomainId
         * @description Canonical trust-domain identifiers shared across the API boundary.
         *
         *     Using a ``StrEnum`` (over an ``AfterValidator`` on ``str``) makes the
         *     allowed values part of the OpenAPI schema as an enum, which gives the
         *     generated frontend client a discriminated string union instead of a
         *     plain ``string``. That removes the duplicated allow-list previously
         *     living in both ``backend/ui/snapshots.py`` (server-side validator) and
         *     ``frontend/src/domain/instances.ts`` (registry), and turns a
         *     cross-boundary drift class into a compile error.
         *
         *     Membership must continue to mirror the frontend's ``TRUST_INSTANCES``
         *     registry. The set is small and rarely changes; adding a new domain is
         *     a coordinated two-side change (this enum + the registry).
         * @enum {string}
         */
        TrustDomainId: "investigator" | "federation" | "bank_alpha" | "bank_beta" | "bank_gamma";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSnapshot"];
                };
            };
        };
    };
    system_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSnapshot"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_session_sessions__session_id__step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_until_idle_sessions__session_id__run_until_idle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_notebook_sessions__session_id__case_notebook_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseNotebookReportSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_notebook_sessions__session_id__case_notebook_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseNotebookReportSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_sessions__session_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_sessions__session_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    component_sessions__session_id__components__component_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                component_id: components["schemas"]["ComponentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_sessions__session_id__probes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    component_interaction_sessions__session_id__components__component_id__interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                component_id: components["schemas"]["ComponentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentInteractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentInteractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
