"""Validate the bank databases and the planted scenarios.

Run AFTER build_banks.py + plant_scenarios.py. Confirms:

  1. Each bank database exists and has the expected schema
  2. Each planted scenario's ground-truth entities are present per
     plant_scenarios.py
  3. **Federated-detectable:** pooling across banks via cross-bank
     name_hash matching recovers all planted entities; layering chain
     forms a closed cycle in the pooled transaction graph
  4. **Single-bank invisible:** no bank can recover the ring structure
     from its own data alone — each bank sees lots of near-threshold
     transactions (legitimate-business-shaped noise) but can't identify
     the cross-bank cycle

Exit code: 0 if all checks PASS, 1 if any FAIL.

Run from repo root:
    uv run python data/scripts/validate_banks.py
"""

from __future__ import annotations

import hashlib
import sqlite3
import sys
from collections import Counter
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
SILOS_DIR = REPO_ROOT / "data" / "silos"

BANK_IDS = ("bank_alpha", "bank_beta", "bank_gamma")

EXPECTED_ENTITY_COUNTS_BY_SCENARIO = {
    "S1": 5,
    "S2": 3,
    "S3": 4,
}
EXPECTED_PEP_COUNT = 1


def check(name: str, condition: bool, detail: str = "") -> bool:
    status = "PASS" if condition else "FAIL"
    suffix = f"  {detail}" if detail else ""
    print(f"  [{status}]  {name}{suffix}")
    return condition


def load_table(bank_id: str, table: str) -> pd.DataFrame:
    db_path = SILOS_DIR / f"{bank_id}.db"
    con = sqlite3.connect(str(db_path))
    df = pd.read_sql(f"SELECT * FROM {table}", con)
    con.close()
    return df


def load_ground_truth_pooled() -> pd.DataFrame:
    """Pooled ground truth across all three banks."""
    frames = []
    for b in BANK_IDS:
        df = load_table(b, "ground_truth_entities")
        df["bank_id"] = b
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def cp_hash(value: str) -> str:
    """Mirror of plant_scenarios.hash_counterparty / build_banks.hash_counterparty."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]


def load_shell_entity_txns(bank_id: str) -> pd.DataFrame:
    """Transactions whose owning customer is a planted shell entity.

    By construction in plant_scenarios.py, every transaction on a shell-
    entity account was generated by the dual-booking scenario planters
    (make_ring_transactions / make_layering_chain_transactions). So this
    join cleanly isolates the scenario-planted, dual-booked transactions
    from the one-sided baseline transactions in build_banks.py.
    """
    db_path = SILOS_DIR / f"{bank_id}.db"
    con = sqlite3.connect(str(db_path))
    df = pd.read_sql(
        """
        SELECT t.transaction_id, t.account_id, t.counterparty_account_id_hashed,
               t.amount, t.transaction_type, t.timestamp,
               g.entity_id, g.scenario, g.role
        FROM transactions t
        JOIN accounts a ON t.account_id = a.account_id
        JOIN ground_truth_entities g ON a.customer_id = g.customer_id
        """,
        con,
    )
    con.close()
    df["bank_id"] = bank_id
    return df


def main() -> int:
    print("Validating bank silo databases...\n")
    fails = 0

    # ---- 1. Database files + schema ----
    print("=== 1. Database files & schema ===")
    for b in BANK_IDS:
        db = SILOS_DIR / f"{b}.db"
        if not check(f"{b}.db exists & non-trivial",
                     db.exists() and db.stat().st_size > 100_000,
                     f"({db.stat().st_size/1024:.0f} KB)" if db.exists() else "(missing)"):
            fails += 1
            continue

        con = sqlite3.connect(str(db))
        cur = con.cursor()
        tables = {r[0] for r in cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()}
        con.close()

        for expected in ("customers", "accounts", "transactions",
                         "suspicious_signals", "ground_truth_entities"):
            if not check(f"  {b} has table `{expected}`",
                         expected in tables):
                fails += 1
    print()

    # ---- 2. Ground-truth entities present ----
    print("=== 2. Planted scenario ground truth ===")
    gt = load_ground_truth_pooled()
    by_entity = gt.groupby("entity_id")
    n_distinct_entities = len(by_entity)

    if not check(f"Total distinct shell entities: 12",
                 n_distinct_entities == 12,
                 f"(actual: {n_distinct_entities})"):
        fails += 1

    for scenario, expected_n in EXPECTED_ENTITY_COUNTS_BY_SCENARIO.items():
        actual_n = gt[gt["scenario"] == scenario]["entity_id"].nunique()
        if not check(f"  {scenario}: {expected_n} distinct entities",
                     actual_n == expected_n,
                     f"(actual: {actual_n})"):
            fails += 1

    n_pep_rows = gt[gt["is_pep"] == 1]["entity_id"].nunique()
    if not check(f"PEP entities: {EXPECTED_PEP_COUNT}",
                 n_pep_rows == EXPECTED_PEP_COUNT,
                 f"(actual: {n_pep_rows})"):
        fails += 1
    print()

    # ---- 3. Cross-bank presence (the federation linkage key) ----
    print("=== 3. Cross-bank entity presence (linkage via name_hash) ===")
    # For each entity_id, how many distinct banks does it appear at?
    banks_per_entity = gt.groupby("entity_id")["bank_id"].nunique()

    s1_entities = gt[gt["scenario"] == "S1"]["entity_id"].unique()
    s2_entities = gt[gt["scenario"] == "S2"]["entity_id"].unique()
    s3_entities = gt[gt["scenario"] == "S3"]["entity_id"].unique()

    # S1: all 5 entities at 2 banks each
    s1_two_bank = all(banks_per_entity[e] == 2 for e in s1_entities)
    if not check("S1 entities at 2 banks each",
                 s1_two_bank,
                 str({e: int(banks_per_entity[e]) for e in s1_entities})):
        fails += 1

    # S2: all 3 entities at 2 banks each (Alpha + Beta)
    s2_two_bank = all(banks_per_entity[e] == 2 for e in s2_entities)
    if not check("S2 entities at 2 banks each (Alpha+Beta only)",
                 s2_two_bank,
                 str({e: int(banks_per_entity[e]) for e in s2_entities})):
        fails += 1

    # Confirm S2 never touches Gamma
    s2_gamma_present = (
        (gt["scenario"] == "S2") & (gt["bank_id"] == "bank_gamma")
    ).any()
    if not check("S2 has zero Gamma presence",
                 not s2_gamma_present):
        fails += 1

    # S3: chain — depends on chain definition; chain_start (1 bank),
    # relays (2 banks), chain_end (2 banks).
    s3_distribution = {e: int(banks_per_entity[e]) for e in s3_entities}
    if not check("S3 chain has start at 1 bank and others at 2 banks",
                 sorted(s3_distribution.values()) == [1, 2, 2, 2],
                 str(s3_distribution)):
        fails += 1
    print()

    # ---- 4. Federated-detectable: cross-bank name_hash matching ----
    print("=== 4. Federated detectability (pooled across banks) ===")
    pooled_customers = []
    for b in BANK_IDS:
        df = load_table(b, "customers")
        df["bank_id"] = b
        pooled_customers.append(df)
    customers_all = pd.concat(pooled_customers, ignore_index=True)

    name_hash_bank_counts = (
        customers_all.groupby("name_hash")["bank_id"].nunique().reset_index(name="n_banks")
    )
    multi_bank = name_hash_bank_counts[name_hash_bank_counts["n_banks"] >= 2]

    # Each of our 12 shell entities should appear with multi-bank
    # presence, EXCEPT S3-A (chain_start, only at Alpha).
    expected_multi_bank_name_hashes = set(
        gt[gt["role"] != "chain_start"]["name_hash"].unique()
    )
    actual_multi_bank_name_hashes = set(multi_bank["name_hash"].tolist())
    recovered = expected_multi_bank_name_hashes & actual_multi_bank_name_hashes
    missing = expected_multi_bank_name_hashes - actual_multi_bank_name_hashes
    if not check(f"All cross-bank shell entities recoverable via name_hash matching",
                 len(missing) == 0,
                 f"(recovered {len(recovered)}/{len(expected_multi_bank_name_hashes)}; "
                 f"missing: {len(missing)})"):
        fails += 1

    # Volume check: pooled cross-bank shell-entity transactions exceed a
    # natural baseline (i.e., the rings produce substantial detected volume).
    shell_name_hashes = set(gt["name_hash"].unique())
    pooled_txns_total = 0
    for b in BANK_IDS:
        accounts = load_table(b, "accounts")
        customers = load_table(b, "customers")
        txns = load_table(b, "transactions")
        # Join txns -> accounts -> customers to filter to shell-entity transactions
        merged = txns.merge(accounts, on="account_id", how="left").merge(
            customers, on="customer_id", how="left"
        )
        n_shell_txns = int(
            merged["name_hash"].isin(shell_name_hashes).sum()
        )
        pooled_txns_total += n_shell_txns

    if not check(f"Pooled shell-entity transactions >= 200",
                 pooled_txns_total >= 200,
                 f"(actual: {pooled_txns_total})"):
        fails += 1
    print()

    # ---- 5. Single-bank invisibility (the federation's whole point) ----
    print("=== 5. Single-bank invisibility ===")
    # For each bank, count near-CTR-threshold transactions. The signal
    # noise should be high enough that no single bank can pick the ring
    # entities out without external linkage.
    for b in BANK_IDS:
        signals = load_table(b, "suspicious_signals")
        n_near_ctr = (signals["signal_type"] == "amount_near_ctr_threshold").sum()
        # A bank with >100 near-CTR alerts has too many candidates to
        # pick the ring out by hand. ANY reasonable number of alerts
        # makes the FP problem real — but >100 is the demo's strongest
        # claim.
        threshold = 50
        if not check(f"{b} near-CTR alerts >= {threshold} (FP volume)",
                     n_near_ctr >= threshold,
                     f"(actual: {int(n_near_ctr)})"):
            fails += 1

    # Single-bank shell-entity recovery: from a single bank's name_hash
    # column alone, you can see each shell entity exists, but you
    # cannot tell which are multi-bank. Demonstrate by counting
    # name_hashes per bank — every single bank sees only its own shells.
    print()
    for b in BANK_IDS:
        n_shells_at_bank = int(
            (gt["bank_id"] == b).sum()
        )
        print(f"  {b} hosts {n_shells_at_bank} shell entities (visible only "
              f"as 'business_checking' customers locally)")
    print()

    # ---- 6. PEP entity attached to S1 ----
    print("=== 6. PEP marker ===")
    pep_rows = gt[gt["is_pep"] == 1]
    pep_scenarios = set(pep_rows["scenario"].unique())
    if not check("PEP entity is in S1",
                 pep_scenarios == {"S1"},
                 f"(scenarios: {pep_scenarios})"):
        fails += 1
    pep_entities = pep_rows["entity_id"].unique().tolist()
    pep_banks = set(pep_rows["bank_id"].unique().tolist())
    print(f"        PEP entity: {pep_entities[0] if pep_entities else 'NONE'}")
    print(f"        PEP present at: {sorted(pep_banks)}")
    print()

    # ---- 7. Layering chain closes a loop ----
    print("=== 7. Layering chain (S3) closes a loop ===")
    s3 = gt[gt["scenario"] == "S3"]
    roles = sorted(s3["role"].unique())
    if not check("S3 has chain_start + chain_relay + chain_end roles",
                 "chain_start" in roles and "chain_end" in roles,
                 f"(roles: {roles})"):
        fails += 1
    # Verify chain_end has accounts at the same bank as chain_start
    # (chain_start is at bank_alpha, chain_end should also include bank_alpha
    # so the chain closes back).
    chain_start_banks = set(s3[s3["role"] == "chain_start"]["bank_id"].unique())
    chain_end_banks = set(s3[s3["role"] == "chain_end"]["bank_id"].unique())
    if not check("Chain start and end overlap at a bank (loop closes)",
                 len(chain_start_banks & chain_end_banks) >= 1,
                 f"(start: {chain_start_banks}, end: {chain_end_banks})"):
        fails += 1
    print()

    # ---- 8. Dual-booking balance closure (shell-entity transactions) ----
    # Every planted transfer should appear as a debit at the sender's bank
    # and a matching credit at the receiver's bank with the same amount
    # and timestamp; the counterparty_hash on each side should equal the
    # SHA-256 of the other side's account_id. We check (a) per-scenario
    # debit/credit count + amount totals, (b) pooled totals, and (c) a
    # strict multiset equality that every debit has its mirror credit.
    print("=== 8. Dual-booking balance closure (shell-entity transactions) ===")
    pooled_shell = pd.concat(
        [load_shell_entity_txns(b) for b in BANK_IDS],
        ignore_index=True,
    )

    for scenario in ("S1", "S2", "S3"):
        s = pooled_shell[pooled_shell["scenario"] == scenario]
        debits = s[s["transaction_type"] == "debit"]
        credits = s[s["transaction_type"] == "credit"]

        if not check(
            f"  {scenario} debit count == credit count",
            len(debits) == len(credits),
            f"(debits {len(debits)}, credits {len(credits)})",
        ):
            fails += 1

        debit_cents = int(round(debits["amount"].sum() * 100))
        credit_cents = int(round(credits["amount"].sum() * 100))
        if not check(
            f"  {scenario} debit total == credit total",
            debit_cents == credit_cents,
            f"(debits ${debit_cents/100:,.2f}, credits ${credit_cents/100:,.2f})",
        ):
            fails += 1

    # Pooled across all scenarios
    all_debits = pooled_shell[pooled_shell["transaction_type"] == "debit"]
    all_credits = pooled_shell[pooled_shell["transaction_type"] == "credit"]
    if not check(
        "Pooled shell debit count == credit count",
        len(all_debits) == len(all_credits),
        f"(debits {len(all_debits)}, credits {len(all_credits)})",
    ):
        fails += 1
    pooled_d = int(round(all_debits["amount"].sum() * 100))
    pooled_c = int(round(all_credits["amount"].sum() * 100))
    if not check(
        "Pooled shell debit total == credit total",
        pooled_d == pooled_c,
        f"(debits ${pooled_d/100:,.2f}, credits ${pooled_c/100:,.2f})",
    ):
        fails += 1

    # Strict 1:1 mirror check.
    # For each debit at sender account S sending to (hashed) receiver R,
    # there must be exactly one credit at some account whose account_id
    # hashes to R, whose counterparty hashes to the same hash of S, with
    # the same amount + timestamp. We do this as multiset equality of
    # (other_side_account_hash, this_side_counterparty_hash, amount, ts).
    debit_keys = Counter(
        zip(
            all_debits["account_id"].map(cp_hash),                  # = receiver's view of sender
            all_debits["counterparty_account_id_hashed"],           # = receiver's account_id hashed
            all_debits["amount"].round(2),
            all_debits["timestamp"],
        )
    )
    credit_keys = Counter(
        zip(
            all_credits["counterparty_account_id_hashed"],          # = sender's account_id hashed
            all_credits["account_id"].map(cp_hash),                 # = receiver's account_id hashed
            all_credits["amount"].round(2),
            all_credits["timestamp"],
        )
    )
    if not check(
        "Every shell debit has a matching shell credit (1:1 mirror)",
        debit_keys == credit_keys,
        f"(unique debit keys {len(debit_keys)}, unique credit keys {len(credit_keys)}, "
        f"unmatched debits {sum((debit_keys - credit_keys).values())}, "
        f"unmatched credits {sum((credit_keys - debit_keys).values())})",
    ):
        fails += 1
    print()

    # Summary
    print("=" * 60)
    if fails == 0:
        print("ALL CHECKS PASSED")
        return 0
    else:
        print(f"FAILED: {fails} check(s)")
        return 1


if __name__ == "__main__":
    sys.exit(main())
