"""Shared contracts for the federated AML agent system."""

from shared.enums import (
    AgentRole,
    AuditEventKind,
    AuditReviewScope,
    BankId,
    MessageType,
    PatternClass,
    PolicyContentChannel,
    PolicyDecision,
    PolicySeverity,
    PrivacyUnit,
    QueryShape,
    ResponseValueKind,
    RouteKind,
    SARPriority,
    SignalType,
    TypologyCode,
)
from shared.identifiers import hash_identifier, is_cross_bank_hash_token
from shared.messages import (
    AggregateActivityPayload,
    AgentMessage,
    Alert,
    AuditEvent,
    AuditPayload,
    AuditReviewRequest,
    AuditReviewResult,
    BankAggregate,
    BoolResponseValue,
    BudgetExhaustedPayload,
    BypassTriggeredPayload,
    ComplianceFinding,
    ConstraintViolationPayload,
    ContributorAttribution,
    CounterpartyLinkagePayload,
    CrossBankHashToken,
    DismissalRationale,
    EntityPresencePayload,
    EvidenceItem,
    FloatResponseValue,
    GraphPatternRequest,
    GraphPatternResponse,
    HashListResponseValue,
    HashString,
    HistogramResponseValue,
    HumanReviewPayload,
    IntResponseValue,
    LtVerdictPayload,
    LocalSiloContributionRequest,
    Message,
    MessageSentPayload,
    OpaqueHashToken,
    PolicyEvaluationRequest,
    PolicyEvaluationResult,
    PolicyRuleHit,
    PrimitiveCallRecord,
    PurposeDeclaration,
    RateLimitPayload,
    RhoDebitedPayload,
    RouteApproval,
    SARAssemblyRequest,
    SARContribution,
    SARContributionRequest,
    SARDraft,
    SanctionsCheckRequest,
    SanctionsCheckResponse,
    SanctionsResult,
    Sec314bQuery,
    Sec314bResponse,
    Sha256Hex,
    reject_demo_customer_names,
    response_value_kind,
)

# Keep public exports alphabetized via Python's default ``sorted()``
# (case-sensitive ASCII: uppercase letters sort before lowercase ones,
# so type classes precede helper functions). Drift is visible when
# adding a contract: ``sorted(__all__)`` should produce no diff against
# this list. Case-insensitive alphabetization was considered and
# declined -- the case-sensitive form is what ``sorted()`` produces by
# default, which means a developer who alphabetizes naively after
# adding an entry gets the right answer without remembering to pass
# ``key=str.casefold``.
__all__ = [
    "AgentMessage",
    "AgentRole",
    "AggregateActivityPayload",
    "Alert",
    "AuditEvent",
    "AuditEventKind",
    "AuditPayload",
    "AuditReviewRequest",
    "AuditReviewResult",
    "AuditReviewScope",
    "BankAggregate",
    "BankId",
    "BoolResponseValue",
    "BudgetExhaustedPayload",
    "BypassTriggeredPayload",
    "ComplianceFinding",
    "ConstraintViolationPayload",
    "ContributorAttribution",
    "CounterpartyLinkagePayload",
    "CrossBankHashToken",
    "DismissalRationale",
    "EntityPresencePayload",
    "EvidenceItem",
    "FloatResponseValue",
    "GraphPatternRequest",
    "GraphPatternResponse",
    "HashListResponseValue",
    "HashString",
    "HistogramResponseValue",
    "HumanReviewPayload",
    "IntResponseValue",
    "LocalSiloContributionRequest",
    "LtVerdictPayload",
    "Message",
    "MessageSentPayload",
    "MessageType",
    "OpaqueHashToken",
    "PatternClass",
    "PolicyContentChannel",
    "PolicyDecision",
    "PolicyEvaluationRequest",
    "PolicyEvaluationResult",
    "PolicyRuleHit",
    "PolicySeverity",
    "PrimitiveCallRecord",
    "PrivacyUnit",
    "PurposeDeclaration",
    "QueryShape",
    "RateLimitPayload",
    "ResponseValueKind",
    "RhoDebitedPayload",
    "RouteApproval",
    "RouteKind",
    "SARAssemblyRequest",
    "SARContribution",
    "SARContributionRequest",
    "SARDraft",
    "SARPriority",
    "SanctionsCheckRequest",
    "SanctionsCheckResponse",
    "SanctionsResult",
    "Sec314bQuery",
    "Sec314bResponse",
    "Sha256Hex",
    "SignalType",
    "TypologyCode",
    "hash_identifier",
    "is_cross_bank_hash_token",
    "reject_demo_customer_names",
    "response_value_kind",
]
